### PR TITLE
try new pinning for lzo

### PR DESCRIPTION
**Pull request by ocefpaf**
Just a test, do not merge.

Ping @isuruf and @jreback.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jreback I pulled `build 2` from the channel, so your CIs should pass now.

I am merging this as a test, but I am not hopeful it'll make a difference.
Let me know how your CIs will perform when `build 3` lands on the channel.

**Comment by jreback** [comment]
@ocefpaf ok, let me PR with an un-pin. I'll post here.

**Comment by jreback** [comment]
with _3 still failing: https://travis-ci.org/pandas-dev/pandas/jobs/282891296

**Comment by isuruf** [comment]
Can you try doing `conda install lzo=2.06` after installing pytables?

**Comment by ocefpaf** [comment]
> Can you try doing `conda install lzo=2.06` after installing pytables?

That would help us isolate `lzo=2.06` as the culprit, but I need to remove `build 3` first, b/c that is pinned to `lzo >=2.09` and restore `build 2`. (I can also do the testing in my fork.)

**Comment by jreback** [comment]
https://travis-ci.org/pandas-dev/pandas/jobs/283125250

trying here

**Pull request merged**
