### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.1 [ci skip]

### LINKED ISSUE #16: rerender for numpy 1.13 pls
xref https://github.com/conda-forge/numexpr-feedstock/issues/9

### PR DESCRIPTION
**Pull request by jreback**
closes #16

### CODE REVIEW

**Comment by jreback** [comment]
@scopatz

**Comment by ocefpaf** [comment]
Why the CI skip?

**Comment by jreback** [comment]
because this is dependent on numexpr which I just kicked off :< (so it will by-definition fail).

**Comment by jreback** [comment]
once that builds I'll re-push it.

**Comment by jreback** [comment]
https://github.com/conda-forge/numexpr-feedstock/pull/10

**Comment by ocefpaf** [comment]
> once that builds I'll re-push it.

The green button can be misleading :smile: I almost cliked during my morning merges of conda-forge :wink:

**Comment by jreback** [comment]
repushed as numexpr now available

**Comment by ocefpaf** [comment]
@jreback consider adding yourself to both `pytables` and `numexpr` teams.

**Pull request merged**
