### PR TITLE
pytables v3.7.0 (supersedes and closes: #75)

### PR DESCRIPTION
**Pull request by avalentino**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #75.

I am a maintainer of the upstream package and I would lice to become also a maintainer for this recipe, so please not that I have added myself (@avalentino) to the list of maintainers.

### CODE REVIEW

**Comment by avalentino** [comment]
@tomkooij could you please give a look to this PR?

**Comment by maxnoe** [comment]
There is an error with an undeclared variable, which I cannot further pin down:

```
Setting up cross-python
ERROR: local variable 'lines' referenced before assignment
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/pytables_1640775690284/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.

```

It would be great to have the conda-forge packages for pytables 2.7!

**Comment by avalentino** [comment]
> There is an error with an undeclared variable in the failing builds, which I cannot further pin down ...

Indeed, the issue seems to be in one of the build scripts but it is only triggered on some of the platforms as far as I can understand

**Comment by avalentino** [comment]
@scopatz could you please give a look to this PR?

**Comment by avalentino** [comment]
Thanks @ocefpaf

**Pull request merged**
