### PR TITLE
pytables 3.8.0

### PR DESCRIPTION
**Pull request by apmorton**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by apmorton** [comment]
Blocked on https://github.com/conda-forge/c-blosc2-feedstock/pull/36

**Comment by apmorton** [comment]
@ocefpaf the remaining build failures are related to resource utilization when running the test suite - they succeed when run locally using `build-locally.py`.  Not sure what to do, but its reporting 16.5G memory usage.  The non-qemu tests use ~300MB.

```
####################################################################################
Resource usage summary:

Total time: 1:08:35.5
CPU usage: sys=0:02:19.2, user=0:53:21.6
Maximum memory usage observed: 16.5G
Total disk usage observed (not including envs): 36.4K
Validating outputs
+ validate_recipe_outputs pytables-feedstock
validation results:
{}
NOTE: Any outputs marked as False are not allowed for this feedstock.
Uploading packages
+ [[ False != \F\a\l\s\e ]]
Final checks
+ touch /home/conda/feedstock_root/build_artifacts/conda-forge-build-done-linux_aarch64_numpy1.21python3.10.____cpython
+ test -f /home/amorton/gh/pytables-feedstock/build_artifacts/conda-forge-build-done-linux_aarch64_numpy1.21python3.10.____cpython
```

**Comment by apmorton** [comment]
So! the travis jobs are failing somewhat at random - and these tests a really slow in general.

Maybe we can "just" forego running them as part of the conda packaging?

**Comment by ocefpaf** [comment]
We can skip ppc but that is something I''d defer to the @conda-forge/pytables team. For now I restart the CIs and let's see if we can get them to pass.

**Comment by apmorton** [comment]
It seems like skipping the tests on qemu platforms was always intended, but broken - `test_on_native_only` was specified, but its been replaced by `test: native`.

I think this should finally be good to merge 🎉

**Pull request merged**
