### PR TITLE
fix pins

### PR DESCRIPTION
**Pull request by dougalsutherland**
I noticed that `lzo` got pulled in from `defaults` when I just installed pytables. This is because it's pinned to `2.06`, while it [should be](https://github.com/conda-forge/conda-forge.github.io/blob/b44a39dbcd919222dee6cae3d7ee82bdf44986ec/scripts/pin_the_slow_way.py#L70) `2.*`, since [they're all compatible](https://abi-laboratory.pro/tracker/timeline/lzo/).

While I was fixing that, I also noticed that `zlib` is pinned too loosely: it's [not always compatible](https://abi-laboratory.pro/tracker/timeline/zlib/), and [the default](https://github.com/conda-forge/conda-forge.github.io/blob/b44a39dbcd919222dee6cae3d7ee82bdf44986ec/scripts/pin_the_slow_way.py#L91) is `1.2.8`.

Also change to the new `numpy` pinning system instead of `x.x`.

### CODE REVIEW

**Comment by dougalsutherland** [comment]
So, apparently `run_test.py` specifically checks that we have `lzo 2.06` on Linux. Is there a specific reason for that? Looks like it's been in there since the feedstock was created.

**Comment by dougalsutherland** [comment]
I'm assuming that's just a relic from earlier days of conda-forge and am removing. @msarahan / @ocefpaf wrote it in https://github.com/conda-forge/staged-recipes/pull/1134/commits/15b5381ac91a9f01faed6eb7168a802e06c2bc91; please correct me if there's some reason it's still needed.

**Comment by scopatz** [comment]
Thanks @dougalsutherland!

**Comment by ocefpaf** [comment]
> I'm assuming that's just a relic from earlier days of conda-forge and am removing. @msarahan / @ocefpaf wrote it in https://github.com/conda-forge/staged-recipes/pull/1134/commits/15b5381ac91a9f01faed6eb7168a802e06c2bc91; please correct me if there's some reason it's still needed.

@dougalsutherland sorry for the late response but you are probably right. No need for that. Thanks for the updates!

**Comment by scopatz** [comment]
@jreback does this fix your issues?

**Pull request merged**
